### ISSUE TITLE
Change order in board

### ISSUE THREAD

**Issue by kluchLProconom** [KhaosCoders/wpf-kanban#2]
Hi, I want to use your library to create a kanban board - but I need to change order of tasks in one column and swimlane, can I do it some way? Or can you add the support for it?

**Comment by Khaos66** [comment]
Hi. The cards are sorted the way they appier in the `ItemsSource` collection. So, just order the collection from top to bottom and you should be good. 
If you need interactive ordering it will be harder, but if you use an `ObservableCollection` as ItemsSource, you can change the order of the items and the view will update.

**Comment by Khaos66** [comment]
I'll close this issue, as you don't seem to have more questions on this.
Feel free to open it again

**Comment by kluchLProconom** [comment]
Ok, we have implemented in easy way. Thanks for your comment and sorry that I have not closed the issue
