### ISSUE TITLE
Static content in cell and headers

### ISSUE THREAD

**Issue by Riccardofull** [KhaosCoders/wpf-kanban#3]
Hello, 

I've two questions:
1) Is it possible to add static content for each cell of the kanban board? Otherwise is there a way to cycle all cells?
2) When the kanban board scrolls, is it possible to keep the headers fixed at the top? 

Thanks,
Regards

**Comment by Khaos66** [comment]
Hi,
1. you can use the KanbanPlainCard. This card has no content by default. You can design your own card with this one. You can find a sample here: https://github.com/KhaosCoders/wpf-kanban/blob/master/Samples/WpfApp1/KanbanPlainCardWindow.xaml
2. this is a good point. I'm afraid it is not possible right now. But I will consider it next time I work on this side project

**Comment by Khaos66** [comment]
You can find fixed column headers in the latest version: [2.0.0](https://www.nuget.org/packages/WPF-Kanban/2.0.0)
Have fun =)
