### ISSUE TITLE
System.NotImplementedException: 'Implement Add'

### ISSUE THREAD

**Issue by KayOpper** [KhaosCoders/wpf-kanban#5]
Hi.

One more question. How can I update the ObservableCollection for the Card Data? May be I want to remove or add a card in the KanbanBoard at runtime. The ObservableCollection.Add methods only works at initialization. If I do the same at runtime, I will get the NotImplementedException. I can help myself be assigning a new ObservableCollection to the KanbanBoard with PropertyChanged. Is this standard or do I make something wrong? All other things work very well.

I found this here but it did not help me:
https://www.reddit.com/r/csharp/comments/idkpb1/systemnotimplementedexception_implement_add/

Thank you

**Comment by Khaos66** [comment]
Thank you for pointing this out! 
It was a bug on my side ;) You did everything right.
I update the sample and release a fixed version in the next few minutes

**Comment by KayOpper** [comment]
Yes. Now it works.
Thank you.
