### ISSUE TITLE
Fixed headers

### ISSUE THREAD

**Issue by KayOpper** [KhaosCoders/wpf-kanban#8]
Hello.

It is not really a new issue as it was already mentioned by Riccardofull. So I just want to confirm that fixed headers at the top of the Kanban Board when scrolling down would be a very user friendly feature. So it would be great if this could be part of a next release whenever you have time for it.

Regards

**Comment by Khaos66** [comment]
You can find fixed headers in the latest version [2.0.0](https://www.nuget.org/packages/WPF-Kanban/2.0.0)
Have fun =)

**Comment by KayOpper** [comment]
Oh. Big new release.
Thank you for the quick implementation.
